In [1]:
import pandas as pd
import re
from dsp_nesta_brain import PROJECT_DIR

from bs4 import BeautifulSoup
import json

SITEMAP_PATH = PROJECT_DIR / 'data/Nesta_sitemap_2024-10-29.csv'

BASE_URL = "https://nesta.org.uk"

In [2]:
import requests
from scraping import scrape

In [3]:
def split_url(url: str) -> list:
    """Split a URL into its components"""
    try:
        return [u for u in url.split('/') if len(u) > 0]
    except:
        return None

def url_to_uid(url: str) -> str:
    """Convert a URL to a UID by removing the base URL and replacing slashes with dashes"""
    uid = url.replace(BASE_URL, "").replace("/", "-")
    uid = re.sub("-$", "", uid)
    return uid

def clean_uid(uid: str) -> str:
    """Remove dash in the beginning of the UID"""
    return re.sub("^-", "", uid)

In [4]:
sitemap_df = (
    pd.read_csv(SITEMAP_PATH)
    # Get the url components
    .assign(site_group = lambda df: df.website.apply(split_url))
    .dropna(subset=['site_group'])
    # Remove home page from the list
    .assign(site_group_len = lambda df: df.site_group.apply(len))
    .query('site_group_len > 0')
    .drop(columns=['site_group_len'])
    # Get the site group
    .assign(site_group = lambda df: df.site_group.apply(lambda x: x[0]))
    .drop_duplicates(subset=['website'])
    # turn views into integers
    .fillna({'views': '0', 'active_users': '0'})
    .assign(views = lambda df: df.views.apply(lambda x: x.replace(',', '')).astype(int))
    .assign(uid = lambda df: df.website.apply(url_to_uid))
    .assign(uid = lambda df: df.uid.apply(clean_uid))
    # remove duplicated uids
    .sort_values('rank', ascending=True)
    .drop_duplicates(subset=['uid'], keep='first')
)

In [5]:
site_groups_df = (
    sitemap_df
    .groupby('site_group')
    .agg(
        n_urls = ('website', 'count'),
        avg_views = ('views', 'mean'),
        total_views = ('views', 'sum'),
    )
    .sort_values('n_urls', ascending=False)
    .reset_index()
)

In [6]:
SITE_GROUPS = [
    'blog',
    'report',
    'feature',
    'team',
    'project',
    'event',
    'press-release',
    'project_updates',
    'toolkit',
    'data-visualisation-and-interactive',
    'areas_of_work',
    'case-study',
    'about-us',
    'introduction-our-strategy',
    'about',
    'fairer-start',
    'healthy-life',
    'sustainable-future',
]

In [7]:
sites_to_scrape_df = sitemap_df.query("site_group in @SITE_GROUPS")
len(sites_to_scrape_df)

9053

In [8]:
sites_to_scrape_df.query("site_group == 'report'").head(5)

,rank,website,views,active_users,views_per_active_user,avg_engagement_time,site_group,uid
5,6,/report/,27773,"14,442",1.92,47s,report,report
31,32,/report/modelling-ways-to-improve-our-health/,7247,"5,198",1.39,49s,report,report-modelling-ways-to-improve-our-health
35,36,/report/nesta-strategy-2030/,6381,"5,193",1.23,23s,report,report-nesta-strategy-2030
40,41,/report/state-of-the-art-analysing-where-art-m...,5359,"4,318",1.24,23s,report,report-state-of-the-art-analysing-where-art-me...
41,42,/report/heat-pumps-a-user-survey/,4959,"3,261",1.52,33s,report,report-heat-pumps-a-user-survey

- Folder where to store the websites htmls (using uids)
- Folder for PDFs and naming convention for the pdfs
- jsonl file for saving metadata (from the website and pdfs names)
- Scraping script that checks the jsonl and scrapes only missing files (using requests); use asyncio if useful
- Processing script that goes through the files and applies the beautifulsoup script, and saves processed text in... a new jsonl?
- Upload the documents on S3, and write getters for getting them

In [9]:
web = sites_to_scrape_df.iloc[44].website
url = f"{BASE_URL}{web}"
url

'https://nesta.org.uk/report/nesta-standards-of-evidence/'

In [20]:
sites_to_scrape_df.head()

,rank,website,views,active_users,views_per_active_user,avg_engagement_time,site_group,uid
2,3,/team/,106714,"29,243",3.65,1m 03s,team,team
3,4,/about-us/,45303,"35,784",1.27,31s,about-us,about-us
5,6,/report/,27773,"14,442",1.92,47s,report,report
7,8,/introduction-our-strategy/,23743,"17,576",1.35,27s,introduction-our-strategy,introduction-our-strategy
8,9,/fairer-start/,23400,"14,832",1.58,54s,fairer-start,fairer-start

In [18]:
# add my email to the headers
result = requests.get(url, timeout=10, headers={'User-Agent': 'karlis.kanders@nesta.org.uk'})

In [19]:
result.status_code

200

In [16]:
import importlib
importlib.reload(scrape)

In [17]:
soup = BeautifulSoup(result.text, 'html.parser')  
scrape.extract_data_layer(soup)

[{'areasOfWork': '',
  'missions': '',
  'projects': '',
  'units': 'Alliance for Useful Evidence',
  'authors': 'Joe Ludlow,Ruth Puttick',
  'contentType': 'report page',
  'title': 'Nesta Standards of Evidence',
  'publishDate': '2013-10-29'}]

In [13]:
pdf_links = scrape.extract_pdf_links(soup, BASE_URL)

In [15]:
scrape.download_pdfs(pdf_links)

2024-10-29 15:41:45,302 - dsp_nesta_brain - INFO - Downloaded: standards_of_evidence.pdf

In [150]:
scrape.scrape(url)

{'text': 'This is a toolkit on how to invent, adopt or adapt ideas that can deliver better results. It features 30 practical social innovation tools that are quick to use and simple to apply.\n\nThe toolkit was created by Nesta in partnership with STBY and Quicksand, and made possible by the Rockefeller Foundation.\n\n\n                    The DIY Toolkit\n                \n\nThe free toolkit includes 30 tried and tested social innovation tools, all grounded in existing theories and practices of innovation, design, and business development.\nAs well as the downloadable full toolkit, each of the individual tools is available in a range of sizes as a pdf template for use in the field, so practitioners can dive straight into action.\nThe DIY toolkit website also features a range of case studies and expert blog posts to help people put the tools into practice.\nThe website is also available in Spanish, Arabic, Mandarin, French and Russian.\nThe original toolkit was designed for people working in development, but the tools are relevant for any project or group.',
 'title': 'DIY Toolkit',
 'date_pub': datetime.datetime(2014, 4, 4, 0, 0)}

# Processing data

In [58]:
# Load jsonl file as pandas dataframe
datapath = PROJECT_DIR / 'data/outputs_2024-10-29/metadata.jsonl'
df = (
    pd.read_json(datapath, lines=True)
    .assign(has_pdf = lambda df: df.pdf_files.apply(len) > 0)
)

In [59]:
df

,_status_code,url,website,uid,site_group,rank,views,status_code,pdf_files,web_metadata,pdf_links,has_pdf
0,200,https://nesta.org.uk/event/,/event/,event,event,11,19203,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
1,200,https://nesta.org.uk/team/,/team/,team,team,3,106714,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
2,200,https://nesta.org.uk/sustainable-future/,/sustainable-future/,sustainable-future,sustainable-future,13,16780,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
3,200,https://nesta.org.uk/healthy-life/,/healthy-life/,healthy-life,healthy-life,12,18488,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
4,200,https://nesta.org.uk/report/,/report/,report,report,6,27773,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
5,200,https://nesta.org.uk/about-us/,/about-us/,about-us,about-us,4,45303,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
6,200,https://nesta.org.uk/toolkit/theory-change/,/toolkit/theory-change/,toolkit-theory-change,toolkit,14,16323,200,[toolkit-theory-change_Resources_2017_version_...,"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,True
7,200,https://nesta.org.uk/project/impact-investments/,/project/impact-investments/,project-impact-investments,project,10,23221,200,[],"[{'areasOfWork': 'Education,Health', 'missions...",NaN,False
8,200,https://nesta.org.uk/introduction-our-strategy/,/introduction-our-strategy/,introduction-our-strategy,introduction-our-strategy,8,23743,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
9,200,https://nesta.org.uk/fairer-start/,/fairer-start/,fairer-start,fairer-start,9,23400,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
10,200,https://nesta.org.uk/toolkit/,/toolkit/,toolkit,toolkit,16,15147,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
11,200,https://nesta.org.uk/team/ravi-gurumurthy/,/team/ravi-gurumurthy/,team-ravi-gurumurthy,team,31,8094,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
12,200,https://nesta.org.uk/blog/,/blog/,blog,blog,23,10442,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
13,200,https://nesta.org.uk/project/mission-studio/,/project/mission-studio/,project-mission-studio,project,24,10243,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
14,200,https://nesta.org.uk/blog/proof-of-concept-pro...,/blog/proof-of-concept-prototype-pilot-mvp-wha...,blog-proof-of-concept-prototype-pilot-mvp-what...,blog,17,14947,200,[],"[{'areasOfWork': 'Government innovation', 'mis...",NaN,False
15,200,https://nesta.org.uk/blog/the-electricity-to-g...,/blog/the-electricity-to-gas-price-ratio-expla...,blog-the-electricity-to-gas-price-ratio-explai...,blog,21,10921,200,[],"[{'areasOfWork': '', 'missions': 'A sustainabl...",NaN,False
16,200,https://nesta.org.uk/toolkit/diy-toolkit/,/toolkit/diy-toolkit/,toolkit-diy-toolkit,toolkit,15,15280,200,"[toolkit-diy-toolkit_DIY_ITA.pdf, toolkit-diy-...","[{'areasOfWork': 'Government innovation', 'mis...",NaN,True
17,200,https://nesta.org.uk/project/centre-collective...,/project/centre-collective-intelligence-design/,project-centre-collective-intelligence-design,project,25,9153,200,[],"[{'areasOfWork': 'Futurescoping', 'missions': ...",NaN,False
18,200,https://nesta.org.uk/blog/10-ways-you-can-help...,/blog/10-ways-you-can-help-improve-young-peopl...,blog-10-ways-you-can-help-improve-young-people...,blog,27,8631,200,[],"[{'areasOfWork': 'Education', 'missions': '', ...",NaN,False
19,200,https://nesta.org.uk/toolkit/collective-intell...,/toolkit/collective-intelligence-design-playbook/,toolkit-collective-intelligence-design-playbook,toolkit,28,8508,200,[toolkit-collective-intelligence-design-playbo...,"[{'areasOfWork': 'Futurescoping', 'missions': ...",NaN,True
20,200,https://nesta.org.uk/blog/9-crowdfunding-platf...,/blog/9-crowdfunding-platforms-for-charities-c...,blog-9-crowdfunding-platforms-for-charities-co...,blog,39,5541,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
21,200,https://nesta.org.uk/feature/innovation-method...,/feature/innovation-methods/accelerator-progra...,feature-innovation-methods-accelerator-programmes,feature,40,5419,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
22,200,https://nesta.org.uk/feature/future-signals-2024/,/feature/future-signals-2024/,feature-future-signals-2024,feature,37,6182,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
23,200,https://nesta.org.uk/blog/the-economics-of-obe...,/blog/the-economics-of-obesity/,blog-the-economics-of-obesity,blog,34,6787,200,"[blog-the-economics-of-obesity_dh_4014481.pdf,...","[{'areasOfWork': '', 'missions': 'A healthy li...",NaN,True
24,200,https://nesta.org.uk/report/modelling-ways-to-...,/report/modelling-ways-to-improve-our-health/,report-modelling-ways-to-improve-our-health,report,32,7247,200,[report-modelling-ways-to-improve-our-health_c...,"[{'areasOfWork': '', 'missions': 'A healthy li...",NaN,True
25,200,https://nesta.org.uk/feature/future-signals-2023/,/feature/future-signals-2023/,feature-future-signals-2023,feature,35,6433,200,[],"[{'areasOfWork': '', 'missions': 'A fairer sta...",NaN,False
26,200,https://nesta.org.uk/report/nesta-strategy-2030/,/report/nesta-strategy-2030/,report-nesta-strategy-2030,report,36,6381,200,[report-nesta-strategy-2030_Nesta_Strategy_Rep...,"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,True
27,200,https://nesta.org.uk/report/state-of-the-art-a...,/report/state-of-the-art-analysing-where-art-m...,report-state-of-the-art-analysing-where-art-me...,report,41,5359,200,[report-state-of-the-art-analysing-where-art-m...,[{'areasOfWork': 'Creative economy &amp; cultu...,NaN,True
28,200,https://nesta.org.uk/feature/innovation-method...,/feature/innovation-methods/standards-evidence/,feature-innovation-methods-standards-evidence,feature,38,5761,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
29,200,https://nesta.org.uk/feature/top-data-visualis...,/feature/top-data-visualisations/live-tube-maps/,feature-top-data-visualisations-live-tube-maps,feature,33,6969,200,[],"[{'areasOfWork': '', 'missions': '', 'projects...",NaN,False
30,200,https://nesta.org.uk/report/heat-pumps-a-user-...,/report/heat-pumps-a-user-survey/,report-heat-pumps-a-user-survey,report,42,4959,200,[report-heat-pumps-a-user-survey_Heat_pump_use...,"[{'areasOfWork': '', 'missions': 'A sustainabl...",[https://nesta.org.uk/documents/2782/Heat_pump...,True
31,200,https://nesta.org.uk/blog/tackling-the-uks-lon...,/blog/tackling-the-uks-loneliness-epidemic/,blog-tackling-the-uks-loneliness-epidemic,blog,46,4627,200,[],"[{'areasOfWork': '', 'missions': 'A healthy li...",[],False
32,200,https://nesta.org.uk/project/lowering-boiler-f...,/project/lowering-boiler-flow-temperature-redu...,project-lowering-boiler-flow-temperature-reduc...,project,43,4863,200,[project-lowering-boiler-flow-temperature-redu...,"[{'areasOfWork': '', 'missions': 'A sustainabl...",[https://nesta.org.uk/documents/2855/NestaCata...,True
33,200,https://nesta.org.uk/press-release/gas-boiler-...,/press-release/gas-boiler-emits-more-annual-co...,press-release-gas-boiler-emits-more-annual-co2...,press-release,45,4683,200,[press-release-gas-boiler-emits-more-annual-co...,"[{'areasOfWork': '', 'missions': 'A sustainabl...",[https://www.ofgem.gov.uk/sites/default/files/...,True
34,200,https://nesta.org.uk/report/the-future-of-skil...,/report/the-future-of-skills-employment-in-2030/,report-the-future-of-skills-employment-in-2030,report,44,4796,200,[report-the-future-of-skills-employment-in-203...,"[{'areasOfWork': 'Education', 'missions': '', ...",[https://nesta.org.uk/documents/585/the_future...,True

In [44]:
n = 19
uid = df.iloc[n].uid
print(uid)

# Load txt file as text string
text = open(PROJECT_DIR / f'data/outputs_2024-10-29/{uid}.txt').read()
print(scrape._scrape(text))

toolkit-collective-intelligence-design-playbook
This playbook was designed by Nesta to help you design and deliver a collective intelligence project.

Collective intelligence is created when people work together, often with the help of technology, to mobilise a wider range of information, ideas and insights to address a social challenge.

Although people have been working together since the dawn of time, collective intelligence has evolved quickly since the start of the digital age.

This playbook will introduce you to activities you can use to orchestrate diverse groups of people, data and technology to achieve your goals.

We call this collective intelligence design.

The playbook contains all of the content you need to design a collective intelligence project. It provides an introduction to collective intelligence and illustrative case studies. It will help you identify when and how to use collective intelligence design, and explain the stages in the collective intelligence design process. It includes a collective intelligence design canvas, plus prompt cards and other activities to help you structure and stretch your thinking.

It is designed to be used by teams or groups working through the activities and exercises together.

You can download an A4 landscape version for free.

We’ve made key parts of the playbook available in larger formats for you to use as a group or in a workshop setting when you’re ready to start designing your collective intelligence project.

The Collective Intelligence Project Design Canvas is a template for people wanting to design a collective intelligence project. You can download the template in A2 size. Use this in conjunction with the design questions and activities included in the playbook.
The Collective Intelligence Prompt Cards provide examples of popular collective intelligence tactics and methods, with a short case study on the back. Use for inspiration at any time, or when indicated in the playbook. Download, print single-sided, cut and fold each card in half.
The Collective Intelligence Design Activities will help deepen or stretch your thinking around particular collective intelligence design questions. Pick and mix those you think will be most relevant. You can download these in A3, to work through with your team more easily.

This is only Version 1.0 of the Collective Intelligence Design Playbook. We’d love your feedback, comments and suggestions for how we make Version 2.0 better! To contribute, follow the link to the Google Docs version.

Alternatively, please send suggestions for additional activities, or your versions of hacked activities and completed canvases to [email protected] with CI Playbook: Version 2.0 as the Subject Line.

In [61]:
pdf_file = df.query("has_pdf").iloc[-1].pdf_files[0]
print(pdf_file)
df.query("has_pdf").iloc[-1].pdf_links[0]

report-the-future-of-skills-employment-in-2030_the_future_of_skills_employment_in_2030_0.pdf

'https://nesta.org.uk/documents/585/the_future_of_skills_employment_in_2030_0.pdf'

In [62]:
import pymupdf
pdf_path = PROJECT_DIR / f'data/outputs_2024-10-29/pdf_files/{pdf_file}'
doc = pymupdf.open(pdf_path)
pages = [page.get_text() for page in doc]

In [63]:
len(pages)

124

In [65]:
# pages[20]